'use strict';

// tests for create
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('create', '/handler.js', 'create');

describe('create', () => {
    it('create',()=>{
 let body = {
         title: "This is title",
     description: "this is desc"
  }
  return wrapped.run({
    body
  }).then(result => {
      expect(result).to.not.be.empty;
      expect(result).to.be.instanceof(Object);
      expect(result).to.have.property('statusCode', 200);
      expect(result).to.have.property('body');
      expect(result.body).not.to.be.empty;
  })  
    })
})




