'use strict';

// tests for getAll
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('getAll', '/handler.js', 'getAll');

describe('getAll', () => {
  before((done) => {
    done();
  });

    it('implement tests here', () => {
      return wrapped.run({}).then(result => {
      expect(result).to.not.be.empty;
      expect(result).to.be.instanceof(Object);
      expect(result).to.have.property('statusCode', 200);
      expect(result).to.have.property('body');
      expect(result.body).not.to.be.empty;
     })
  });
});
