'use strict';

// tests for getOne
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('getOne', '/handler.js', 'getOne');

describe('getOne', () => {
  before((done) => {
    done();
  });
  let pathParameters = {
   "id":"634dd1979e76ad47905db87f"
  }
  it('implement tests here', async () => {
    const result = await wrapped.run({
      pathParameters
    });
      expect(result).to.be.instanceof(Object);
      expect(result).to.have.property('statusCode', 200);
      expect(result).to.have.property('body');
      expect(result.body).not.to.be.empty;
  });
});
